spring:
  application:
    name: bookmarker-api
  datasource:
    url: jdbc:h2:mem:bookmarkdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    locations: classpath:/db/migration/{vendor}
